# Generated by Django 5.2.8 on 2026-05-15 15:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MosaicJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('time_window_days', models.PositiveIntegerField(default=7)),
                ('selected_sensors', models.JSONField(default=list)),
                ('target_crs', models.CharField(default='EPSG:32643', max_length=32)),
                ('resolution', models.FloatField(default=10.0)),
                ('max_cloud_cover', models.FloatField(default=40.0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='created', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('output_cog', models.FileField(blank=True, null=True, upload_to='mosaics/')),
                ('preview_html', models.FileField(blank=True, null=True, upload_to='previews/')),
                ('output_bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('output_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('roi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosaic_jobs', to='geodata.regionofinterest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stac_id', models.CharField(max_length=512, unique=True)),
                ('collection', models.CharField(max_length=128)),
                ('sensor', models.CharField(choices=[('sentinel-2-l2a', 'Sentinel-2 L2A'), ('sentinel-1-rtc', 'Sentinel-1 RTC')], max_length=64)),
                ('acquired_at', models.DateTimeField()),
                ('cloud_cover', models.FloatField(blank=True, null=True)),
                ('footprint', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('assets', models.JSONField(blank=True, default=dict)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-acquired_at'],
                'indexes': [models.Index(fields=['sensor', 'acquired_at'], name='geodata_sat_sensor_b4159b_idx'), models.Index(fields=['collection'], name='geodata_sat_collect_bc7a5e_idx')],
            },
        ),
    ]
