# Generated by Django 5.2.8 on 2026-08-24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geodata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosaicjob",
            name="rgb_bounds",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="mosaicjob",
            name="rgb_cog",
            field=models.FileField(blank=True, null=True, upload_to="mosaics/rgb/"),
        ),
        migrations.AddField(
            model_name="mosaicjob",
            name="rgb_preview",
            field=models.FileField(blank=True, null=True, upload_to="previews/rgb/"),
        ),
        migrations.AddField(
            model_name="mosaicjob",
            name="sar_bounds",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="mosaicjob",
            name="sar_cog",
            field=models.FileField(blank=True, null=True, upload_to="mosaics/sar/"),
        ),
        migrations.AddField(
            model_name="mosaicjob",
            name="sar_preview",
            field=models.FileField(blank=True, null=True, upload_to="previews/sar/"),
        ),
    ]
